name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps: 

    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py


A.
src/addition.py

def add(a,b):
  return a+b

def test_add():
  assert add(1,2) == 3
  assert add(1,-1) == 0

git init
git status
git add .
git commit -m "First commit"
paste that link in …or create a new repository on the command line(in ur git hub acc)

git push -u origin main/ master

got to settings>runner>windows 
$ mkdir actions-runner; cd actions-runner


curl -L -o actions-runner-win-x64-2.321.0.zip https://github.com/actions/runner/releases/download/v2.321.0/actions-runner-win-x64-2.321.0.zip

unzip actions-runner-win-x64-2.321.0.zip

./config.cmd --url https://github.com/anahhgha/mira --token BM4XPWLIUWQU2H4UROPP52LHS4FV6

in github account>actions >first commit>view workflow
